language: android

notifications:
  email:
    -  moses@futurice-nonda.flowdock.com 

env:
  global:
    - TERM=dumb
    - ANDROID_API_LEVEL=23
    - ANDROID_EMULATOR_LEVEL=19
    - ANDROID_BUILD_TOOLS_VERSION=23.0.1
    - ABI=armeabi-v7a
    - ADB_INSTALL_TIMEOUT=8 # minutes         
    - INSTALL_TIMEOUT=8 # minutes        

sudo: false
jdk: oraclejdk8

# Update to the lastest JDK8
addons:
  apt:
    packages:
      - oracle-java8-installer

android:
  components:
    - build-tools-${ANDROID_BUILD_TOOLS_VERSION}
    - android-${ANDROID_API_LEVEL}
    - sys-img-armeabi-v7a-android-${ANDROID_EMULATOR_LEVEL}
    - platform-tools
    - tools
#    - extra
#    - add-on
#    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
#    - addon-google_apis-google-${ANDROID_API_LEVEL}
    - extra-android-support

  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'android-sdk-preview-license-.+'

before_script:
#    - android update sdk --no-ui
    - android create avd --force -n nexus -t android-${ANDROID_EMULATOR_LEVEL} -d "Nexus 6" --abi default/${ABI}
    - emulator -avd nexus -no-skin -no-audio -no-window &
    - cd ./ReactiveCascade

script:
    - gradle clean build
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
    - gradle connectedCheck
